"""Add transaction

Revision ID: 8ba9d958bb78
Revises: d72cfd2ac99a
Create Date: 2022-11-15 18:17:50.661446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba9d958bb78'
down_revision = 'd72cfd2ac99a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('datetime', sa.DateTime(), nullable=False),
                    sa.Column('credit_ticker', sa.String(
                        length=20), nullable=False),
                    sa.Column('debit_ticker', sa.String(
                        length=20), nullable=False),
                    sa.Column('price', sa.Numeric(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['credit_ticker'], ['asset.ticker'], ),
                    sa.ForeignKeyConstraint(
                        ['debit_ticker'], ['asset.ticker'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('asset', sa.Column(
        'amount', sa.BigInteger(), nullable=False))
    op.add_column('asset', sa.Column(
        'shares_in_lot', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'shares_in_lot')
    op.drop_column('asset', 'amount')
    op.drop_table('transaction')
    # ### end Alembic commands ###
