# Generated by Django 4.1.3 on 2022-11-16 04:02

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_transaction_replace_date_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=6,
                                                   default_currency='RUB',
                                                   max_digits=14),
        ),
    ]
