# Generated by Django 4.1.3 on 2022-11-20 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_cache_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='lots',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='asset',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lots',
            field=models.BigIntegerField(default=0),
        ),
    ]
